version: "3.5"
networks:
  dev:

services:
  # marketmaker:
  #   container_name: mm
  #   image: "jessmillar/marketmaker:latest"
  #   networks:
  #     - "dev"
  #   ports:
  #     - 7997:8000
  redis:
    hostname: redis
    container_name: mm-redis
    image: redis:6-alpine
    networks:
      - "dev"
    ports:
      - "6379:6379"
  rabbit:
    container_name: mm-dev-rabbit
    image: "jessmillar/dev-rabbit-x86:chaos__f13d33c__20221121"
    networks:
      - "dev"
    ports:
      - 1885:1885
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 15674:15674
      - 25672:25672
    env_file: ./for_docker/dev_vhost.env
    environment:
      - RABBITMQ_USERNAME=smqPublic
      - RABBITMQ_PASSWORD=smqPublic
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/tmp/rabbit_definitions.json"
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_stomp,rabbitmq_web_stomp,rabbitmq_mqtt
    volumes:
      - ./for_docker/dev_rabbitmq.conf:/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.conf:ro
